name: Container
on: push
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    containers:
      image: node:19-alpine
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:19-alpine
        with: 
          entrypoint: ['/bin/echo']
          args: ['Hello World']
      - name: Log node version
        uses: docker://node:19-alpine
        with: 
          entrypoint: ['/uar/local/bin/node', '-v']

  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"

    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get user
        run: curl http://localhost:3001/api/users