# name: ENV Variables
# on: push
# env:
#   WF_ENV: Available to all jobs
#   WF_SECRET_ENV: ${{ secrets.WF_SECRET_ENV }}
#   THETOKEN: ${{ secrets.GITHUB_TOKEN }}
# jobs:
#   log-env:
#     runs-on: ubuntu-latest
#     env:
#       JOB_ENV: Available to all steps
#     steps:
#       - name: Log ENV Variable 1
#         env:
#           STEP_ENV: Available to only this step
#         run: |
#           echo "==> WF_ENV: ${WF_ENV}"
#           echo "==> JOB_ENV: ${JOB_ENV}"
#           echo "==> STEP_ENV: ${STEP_ENV}"
#           echo "==> WF_SECRET_ENV: ${WF_SECRET_ENV}"
#           echo "==> THETOKEN: ${THETOKEN}"
      # - name: Log ENV Variable 2
      #   run: |
      #     echo "==> WF_ENV: ${WF_ENV}"
      #     echo "==> JOB_ENV: ${JOB_ENV}"
      #     echo "==> STEP_ENV: ${STEP_ENV}"


  # log-default-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print all Default Environments
  #       run: |
  #         echo "==> GITHUB_ACTION: ${GITHUB_ACTION}"
  #         echo "==> GITHUB_ENV: ${GITHUB_ENV}"
  #         echo "==> GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
  #         echo "==> GITHUB_PATH: ${GITHUB_PATH}"
  #         echo "==> GITHUB_REF: ${GITHUB_REF}"
  #         echo "==> GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
  #         echo "==> GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
  #         echo "==> RUNNER_NAME: ${RUNNER_NAME}"
  #         echo "==> GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
  #         echo "==> GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"




name: Create issue on commit
on: [ push ]
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Push a random file
        run: |
          pwd
          ls -a
          git init 
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_ACTOR/${GITHUB_REPOSITORY}.git"
          git config --global user.email "sang.khuu@karrostech.com"
          git config --global user.name "sangkhuu"
          git fetch
          git checkout develop
          git branch --set-upstream-to=origin/develop
          git pull
          ls -a
          echo $RANDOM >> random.txt
          git add -A
          git commit -m "create random.txt file"
          git push


      # - name: Create issue using REST API
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/issues \
      #     --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "title": "Automated issue for commit: ${{ github.sha }}",
      #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
      #       }' \
      #     --fail





