name: Matrix include exclude example
on: push
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node_version: [6,8,10]
        include:
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: macos-latest
            node_version: 6
          - os: ubuntu-latest
            node_version: 10
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version before
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node_version }}
      - name: Log node version after
        run: |
          node -v
          echo ${IS_UBUNTU_8}
